import * as fs from 'fs';
import * as path from 'path';
import { type VerificationResult, countErrors, countWarnings } from './bundle.js';

/**
 * Generate a markdown snippet suitable for a GitHub PR description.
 * Uses relative paths for screenshots (assumes artifacts are committed or linked).
 */
export function formatForPR(result: VerificationResult): string {
  const projectName = path.basename(process.cwd());
  const durationSec = Math.round(result.durationMs / 1000);

  let totalErrors = 0;
  let totalWarnings = 0;

  let md = `## Visual Verification — ProofShot

| Page | Status | Screenshot |
|------|--------|------------|
`;

  for (const page of result.pageResults) {
    const errors = countErrors(page.errors);
    const warnings = countWarnings(page.consoleOutput);
    totalErrors += errors;
    totalWarnings += warnings;

    const status = errors > 0 ? '⚠️ Errors' : '✅ OK';
    const relativeSS = path.relative(process.cwd(), page.screenshotPath);
    md += `| \`${page.page}\` | ${status} | ![${page.page}](${relativeSS}) |\n`;
  }

  md += `
**Framework:** ${result.framework} | **Pages:** ${result.pageResults.length} | **Errors:** ${totalErrors} | **Warnings:** ${totalWarnings} | **Duration:** ${durationSec}s
`;

  if (result.videoPath) {
    const relativeVideo = path.relative(process.cwd(), result.videoPath);
    md += `\n**Video:** [Session recording](${relativeVideo})\n`;
  }

  md += `\n<sub>Generated by [ProofShot](https://github.com/AmElmo/proofshot)</sub>\n`;

  return md;
}

/**
 * Write PR-formatted output to a file or stdout.
 */
export function writePRFormat(
  result: VerificationResult,
  outputPath?: string,
): string {
  const md = formatForPR(result);
  if (outputPath) {
    fs.writeFileSync(outputPath, md);
    return outputPath;
  }
  return md;
}

// ─── URL-based PR comment format (for GitHub upload) ───

export interface PRCommentData {
  description: string | null;
  sessionCount: number;
  screenshots: Map<string, string>; // filename → GitHub asset URL
  video: { url: string; renderMode: 'embed' | 'link' } | null;
  errorCount: number;
  verificationStatus: 'passed' | 'failed' | 'unknown';
  assertionFailureCount: number;
  failedActionCount: number;
  incompleteReasons: string[];
  branch: string;
  commitSha: string;
}

function escapeMarkdownText(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/([\\`*_[\]{}()#+\-.!|])/g, '\\$1')
    .replace(/\r?\n/g, ' ');
}

/**
 * Generate markdown for a GitHub PR comment with embedded uploaded assets.
 * Uses GitHub asset URLs so images and video render inline.
 */
export function formatPRComment(data: PRCommentData): string {
  let md = `## ProofShot Verification\n\n`;

  if (data.description) {
    md += `> ${escapeMarkdownText(data.description)}\n\n`;
  }

  const status = data.verificationStatus === 'passed'
    ? '✅ Verification passed'
    : data.verificationStatus === 'failed'
      ? '❌ Verification failed'
      : '⚠️ Verification status unknown';
  md += `${status}\n\n`;

  const failureCounts: string[] = [];
  if (data.errorCount > 0) failureCounts.push(`${data.errorCount} console/server error(s)`);
  if (data.assertionFailureCount > 0) failureCounts.push(`${data.assertionFailureCount} assertion failure(s)`);
  if (data.failedActionCount > 0) failureCounts.push(`${data.failedActionCount} failed action(s)`);
  if (failureCounts.length > 0) md += `**Failures:** ${failureCounts.join(' · ')}\n\n`;

  if (data.incompleteReasons.length > 0) {
    md += `**Evidence issues:**\n\n`;
    for (const reason of data.incompleteReasons) md += `- ${escapeMarkdownText(reason)}\n`;
    md += '\n';
  }

  // Video (GitHub renders video URLs as playable embeds)
  if (data.video) {
    md += `### Recording\n\n`;
    if (data.video.renderMode === 'embed') {
      md += `${data.video.url}\n\n`;
    } else {
      md += `[Session recording](${data.video.url})\n\n`;
    }
  }

  // Screenshots
  if (data.screenshots.size > 0) {
    md += `### Screenshots\n\n`;

    if (data.screenshots.size <= 3) {
      for (const [filename, url] of data.screenshots) {
        const label = filename.replace(/\.png$/, '').replace(/^step-/, '');
        const escapedLabel = escapeMarkdownText(label);
        md += `**${escapedLabel}**\n\n`;
        md += `![${escapedLabel}](${url})\n\n`;
      }
    } else {
      md += `<details>\n<summary>View ${data.screenshots.size} screenshots</summary>\n\n`;
      for (const [filename, url] of data.screenshots) {
        const label = filename.replace(/\.png$/, '').replace(/^step-/, '');
        const escapedLabel = escapeMarkdownText(label);
        md += `**${escapedLabel}**\n\n![${escapedLabel}](${url})\n\n`;
      }
      md += `</details>\n\n`;
    }
  }

  // Footer
  md += `---\n`;
  md += `<sub>`;
  md += `Branch: ${escapeMarkdownText(data.branch)}`;
  if (data.commitSha) {
    md += ` · Commit: ${escapeMarkdownText(data.commitSha.slice(0, 7))}`;
  }
  md += ` · ${data.sessionCount} session(s)`;
  md += `</sub>\n`;
  md += `<sub>Generated by [ProofShot](https://github.com/AmElmo/proofshot)</sub>\n`;

  return md;
}
